{% set data = load_setup_py_data() %}
{% set name = "Stoner" %}
{% set file_ext = "tar.gz" %}


package:
  name: '{{ name|lower }}'
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 1
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - pytest
    - pytest-runner

  run:
  - python
  - cycler >=0.10.0
  - dask >=2020.12.0
  - fabio >=0.11.0
  - filemagic >=1.6
  - h5py >=3.3.0
  - hyperspy >=1.6.4
  - image-registration >=0.2.4
  - imreg_dft >=2.0.0
  - lmfit >=1.0.0
  - matplotlib >=3.4.3
  - memoization >=0.3.1
  - nptdms >=1.1.0
  - numpy >=1.21.2
  - python-dateutil >=2.8.2
  - scikit-image >=0.18.3
  - scipy >=1.7.1
  - seaborn >=0.11.2
  - statsmodels >=0.13.0
  - tabulate >=0.8.9
  - urllib3 >=1.26.7

about:
  home: https://github.com/gb119/Stoner-PythonCode/
  license: GNU General Public License (LGPL)
  license_family: GPL
  license_file: ''
  summary: Library to help write data analysis tools for experimental condensed matter physics.
  description: The Stoner Python package is a set of utility classes for writing data analysis code. It was written within the Condensed Matter Physics group at the University of Leeds as a shared resource for quickly writing simple programs to do things like fitting functions to data, extract curve parameters, churn through large numbers of small text data files and work with certain types of scientific image files.
