version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 1500
  method-complexity:
    config:
      threshold: 15
  method-count:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
plugins:
  sonar-python:
    enabled: true
exclude_patterns:
  - "build/"
  - "dist/"
  - "recipe/"
  - "sample-data/"
  - "scripts/"
  - "Stoner.egg-info/"
  - "tests/"
  - "doc/"