doc-warnings: true
test-warnings: false
strictness: medium
max-line-length: 160
#uses:	
autodetect: true
#requirements:
ignore-patterns:
  - ^.*kgui\.py$
python-targets:
  - 2
  - 3
pylin:
  disable:
    - protected-access