notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always

language: python
dist: "xenial"
sudo: true
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies

services:
  - xvfb


# Setup anaconda
install:
  - sudo apt-get install tesseract-ocr
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --append channels phygbu
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  # This will ensure we collect all the necessary dependencies so long as master doesn't change them!
  - conda install --yes stoner
  # Force upgraded scikit-image
  # - conda install --yes scikit-image
  # Hyperspy is now an optional dependency
  - conda install --yes -c conda-forge hyperspy
  # Now we unistall the stable stoner - use force to stop downgrading packages!
  - conda remove --yes --force stoner
  - pip install opencv_python
  - pip install coveralls
  - pip install .

# command to run tests
script: coverage run --source=Stoner setup.py test

after_success:
  coveralls