notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always

language: python
dist: "bionic"
sudo: true
python:
    - "3.6"
    - "3.7"
  
virtualenv:
  system_site_packages: false

env:
  - NUMBA=1
  - NUMBA=0

# jobs:
#     excelude:
#       - python: 3.6
#       - env: NUMBA = 0
# # command to install dependencies

services:
  - xvfb


# Setup anaconda

before_install:

  # Here we just install Miniconda, which you shouldn't have to change.

  - sudo apt-get install tesseract-ocr
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda init bash
  - source ~/.bashrc
  - conda config --set always_yes yes --set changeps1 no
  - conda config --append channels phygbu
  - conda config --append channels conda-forge
  - conda config --set channel_priority strict
  - conda update -q conda
  - conda info -a
  
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  # Useful for debugging any issues with conda

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION stoner pandas
  - conda activate test-environment
  # This will ensure we collect all the necessary dependencies so long as master doesn't change them!
  # Hyperspy is now an optional dependency for 3.6 onwards
  - conda install hyperspy
  # Now we unistall the stable stoner - use force to stop downgrading packages!
  - conda remove --yes --force stoner
  - if [[ "$NUMBA" == "0" ]]; then conda remove --yes --force numba; fi
  - pip install coveralls
  - pip install --no-deps .

# command to run tests
script: coverage run --source=Stoner setup.py test

after_success:
  coveralls