name: pytest
on: push
jobs:
  run_pytest:
    name: run-tests (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7","3.8","3.9"]
        os: ["ubuntu-latest"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          $CONDA/bin/conda env update --file environment.yml --name base
      - name: Conda info
        run: $CONDA/bin/conda info
      - name: Conda list
        run: $CONDA/bin/conda list
      - name: install package
        run: $CONDA/bin/pip install --no-deps .
      - name: Run headless test
        run: sudo apt-get install xvfb
      - name: Test with xvfb
        run: xvfb-run --auto-servernum $CONDA/bin/pytest  -n `python -c 'import os;print(min(12,os.cpu_count()))'` --cov-report=. --cov=Stoner
      - uses: bcomnes/cleanup-xvfb@v1
      - name: Run Coveralls
      - uses: AndreMiras/coveralls-python-action@v20201129
        with:
          parallel: true
          flag-name: python-${{ matrix.python-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
  coverage-finish:
    needs: run_pytest
    runs-on: ubuntu-latest
    steps:
      - uses: AndreMiras/coveralls-python-action@v20201129
        with:
          parallel-finished: true
